# Generated by Django 3.1.3 on 2021-03-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('total_cost', models.IntegerField()),
                ('remaining_cost', models.IntegerField()),
                ('treatment_date', models.ManyToManyField(related_name='dates', to='patientinfo.Appointment')),
            ],
        ),
    ]
