# Generated by Django 3.1.3 on 2021-03-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0003_auto_20210313_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='appointment',
            field=models.ManyToManyField(related_name='patient_treat', to='patientinfo.Treatment'),
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_date',
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
