# Generated by Django 3.1.3 on 2021-03-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0004_auto_20210315_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='total_cost',
            new_name='paid_cost',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='appointment',
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_treat', to='patientinfo.patients'),
        ),
    ]
