# Generated by Django 3.1.3 on 2021-03-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0007_auto_20210316_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='patient',
            new_name='patient_name',
        ),
    ]
